version: '3.8'

services:

  backend:
    build: ./backend
    command: uvicorn main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    env_file:
      - backend/app/.env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend

volumes:
  caddy-data:
  caddy-config: